### ISSUE TITLE
Exponentiation?

### ISSUE THREAD

**Issue by chadbrewbaker** [snowleopard/alga#1]
I've been dabbling with taking all the middle school algebraic identities and expressing them as type signature refactorings:

http://chadbrewbaker.github.io/algebra/haskell/functional/programming/2016/01/27/algebraRules.html

Have you tried adding an exponentiation operator to your graph algebra? If so would it correspond directly to all functions from graph A to graph B, or would it be more esoteric?

**Comment by snowleopard** [comment]
Hey @chadbrewbaker! Sorry, just noticed the issue -- I didn't expect so much interest to this repo, so I wasn't even watching it :)

One simple way to define exponentiation is via the `connect` that is similar to multiplication: 
```haskell
(^) :: Graph g => g -> Int -> g
g^0 = empty
g^n = g^(n-1) `connect` g
```
Although this seems natural, the result is a bit boring:
```haskell
g^0 = empty
g^1 = g
g^2 = g `connect` g -- This is a clique on vertices in g
g^3 = g `connect` g `connect` g = g^2 -- via the decomposition axiom
...
g^n = g^2
```
So, we only have three different values `g^0`, `g^1` and `g^2 = g^3 = g^4 ...`.

At this point I don't know of any other definitions of the exponent that make sense algebraically.

**Comment by snowleopard** [comment]
By the way, the `(^)` from Prelude almost works as desired. The only problem with it is that it returns `1` for `g^0` which is not what we want, we want it to return the multiplicative identity, which is `empty` in our case.
