### ISSUE TITLE
Make the Internal modules smaller

### ISSUE THREAD

**Issue by ndmitchell** [snowleopard/alga#10]
I'd suggest _only_ exposing the data type in the internal, so people only import it if they need the internals, not just because it's a handy source of all the functions. Another way to go might be to have `Data.Graph.Internal` which has all the internal definitions, and then hide the other `Internal` modules from Cabal?

**Comment by snowleopard** [comment]
I agree that internal modules should be as small as possible, but aren't they already minimal? Unfortunately some functions got pulled into them because they are used by the `Show` instances.

Could you point an example of a function, which should be removed?

One option is to move `Show` instances outside, which would require making them orphan, but that's probably not a big deal since these are our instances.

**Comment by ndmitchell** [comment]
Algebra.Graph.AdjacencyMap.Internal exports `newtype AdjacencyMap = ...`, plus `empty`, `vertex` etc. I would have it literally export _only_ the newtype. That requires a `RealInternal` module with the full thing in, everything in the normal one, and only the internals in Internal. At the moment someone might chose to use Internal just to get things like empty, which isn't what you want.

**Comment by snowleopard** [comment]
Oh, `empty` and friends should surely be moved out.

I think I put them into `Internal` because they use the constructor i.e. `empty = AdjacencyMap $ Map.empty`, but the constructor is available in the main module too!

I'll fix this.

What's your opinion on `Show`? Shall it stay internal?

**Comment by ndmitchell** [comment]
I'm suggesting you put _everything_ into `RealInternal`, and in `Internal` only reexport the data type and constructor. That way `Show` can go in `RealInternal` - best to avoid orphan instances even internally.

**Comment by snowleopard** [comment]
Hmm, `RealInternal` seems unsatisfactory -- if we hide it in Cabal, does this mean that users won't be able to see the source in Haddock?

**Comment by ndmitchell** [comment]
Yes.

**Comment by ndmitchell** [comment]
To be honest, my usual approach is to avoid giving the users access to the internals at all - although I can see why in this instance it might be more reasonable - since the data type is specifying an implementation.

**Comment by snowleopard** [comment]
Right, let me do some experiments tonight, and I'll report back what I can do.

**Comment by ndmitchell** [comment]
In fact, just hollowing out so internal only has the data type plus instances might be enough.

**Comment by snowleopard** [comment]
@ndmitchell Everything worked well with `AdjacencyMap`. I left the data type, instances and the `consistent` function, which is not exported from the main module. 

https://github.com/snowleopard/alga/blob/master/src/Algebra/Graph/AdjacencyMap/Internal.hs

I'll do the same with other internal modules.

**Comment by snowleopard** [comment]
@ndmitchell Done! The only annoyance is that I had to introduce `Algebra.Graph.Relation.InternalDerived` for derived binary relations (such as `ReflexiveRelation`), but now all internal modules are minimal.
