### ISSUE TITLE
Add isAcyclic, topSort, dfs and other graph analysis functions to ToGraph

### ISSUE THREAD

**Issue by fosskers** [snowleopard/alga#105]
Or likewise, `isCircular`. Basically, a top-level function to determine if some `Graph` type is a DAG or not.

As [last time](https://github.com/snowleopard/alga/issues/85) (thanks again), I suspect there's some composition of the exposed primitives that "just works", but nothing jumped out at me after a brief scan of the API.

Thoughts?

**Comment by snowleopard** [comment]
@fosskers Thanks! I agree, this is a useful function to add. If you don't necessarily need a polymorphic function, the implementation is quite simple:

```haskell
isDag :: Ord a => AdjacencyMap a -> Bool
isDag = isJust . topSort
```

You'll just need to convert your graph data type to `AdjacencyMap`.

With the new `ToGraph` type class (coming soon in version `0.2`), I believe we could even add it as a separate method.

**Comment by fosskers** [comment]
Ah ha! So it was just a simple thing. And luckily for me, I'm already using `AdjacencyMap`.

**Comment by fosskers** [comment]
So `isJust . topSort` tells us *if* there's a cycle... would it be hard to report the values of the vertices that are *causing* the cycle?

**Comment by snowleopard** [comment]
@fosskers To find the cycle, you can use the [`scc` function](https://hackage.haskell.org/package/algebraic-graphs-0.1.1.1/docs/Algebra-Graph-AdjacencyMap.html#v:scc). It returns you a graph whose vertices are strongly-connected components, and if any component contains more than a single vertex it is a cycle. 

Here is one possible way to use is: 

```haskell
cycles :: Ord a => AdjacencyMap a -> [AdjacencyMap a]
cycles x = [ induce (`Set.member` c) x | c <- cs ]
  where
    cs = filter (\c -> Set.size c > 1) $ vertexList (scc x)
```

We obtain the list `cs` which contains non-singleton components (i.e. cycles), and then compute corresponding induced subgraphs of the original graph. As a result you can see all cycles in isolation.

For example:

```haskell
> cycles $ path [1, 2, 3]
[]

> cycles $ circuit [1, 2, 3]
[edges [(1,2),(2,3),(3,1)]]

> cycles $ circuit [1, 2, 3] `overlay` path [3, 4, 5] `overlay` circuit [5, 6, 7]
[edges [(1,2),(2,3),(3,1)],edges [(5,6),(6,7),(7,5)]]
```

**Comment by fosskers** [comment]
Holy crap that's fantastic. I'm going to try that out right away.

**Comment by fosskers** [comment]
Alright, looking good! Thanks a lot, once again.

**Comment by snowleopard** [comment]
@fosskers Great! I'll keep this issue open -- `isAcyclic` seems like a useful function to add to the API.

**Comment by fosskers** [comment]
Woops, my bad.
