### ISSUE TITLE
Refactor ToGraph

### ISSUE THREAD

**Issue by ndmitchell** [snowleopard/alga#11]
Should it be `Graph t => ToGraph t`, then you can ditch the associated type family on `ToGraph` reusing the parent one.

**Comment by snowleopard** [comment]
The `ToVertex` family is a little annoying, but making `Graph` a superclass limits the number of instances. For example, something like `Data.Graph.Graph` can be made an instance of `ToGraph` easily, but it's much harder (and probably doesn't make much sense) to make it an instance of `Graph`.

Same goes for types like `[(a, a)]` (or even `[a]`) -- one could easily wrap these into a newtype and define `ToGraph` instances, gaining useful interoperability with the library.

**Comment by ndmitchell** [comment]
OK, that makes sense.
