### ISSUE TITLE
Use new cartesianProduct from containers?

### ISSUE THREAD

**Issue by subttle** [snowleopard/alga#111]
Hi, 
Awesome project you have! I have one very minor comment to make.
I noticed that you're using your own `setProduct` function: https://github.com/snowleopard/alga/blob/76d01ae5ea12279505c92238fb7dc771dcb1e19e/src/Algebra/Graph/Relation/Internal.hs#L173 I just wanted to make sure you are aware that there was a `cartesianProduct` function recently added to containers (Since: containers-0.5.11)! And luckily you're on a stackage lts version which already has it:
 https://www.stackage.org/haddock/lts-12.4/containers-0.5.11.0/Data-Set.html#v:cartesianProduct
Cheers.

**Comment by snowleopard** [comment]
Hello Ian, thank you!

I wasn't aware of `cartesianProduct`, we should definitely switch to it. Would you like to send a PR? If not, no problem, I can fix this too.
