### ISSUE TITLE
Finish rewrite rules to optimize "transpose . star" everywhere

### ISSUE THREAD

**Issue by nobrakal** [snowleopard/alga#116]
This is what remains to be done after the merge of #107 

The objective is to use rewrite rules to optimize `transpose . star` and remove the need of something like a `starTranspose` function.

This is already made for all modules except `Algebra.Graph.Relation` for which the actual solution seems not to be working.

Ideally `transpose . stars` will optimized away. This is already the case for `Algebra.Graph` and `Algebra.Graph.NonEmpty`.

The following set of rules is used for now:

```Haskell
{-# RULES
"transpose/Empty"    transpose Empty = Empty
"transpose/Vertex"   forall x. transpose (Vertex x) = Vertex x
"transpose/Overlay"  forall g1 g2. transpose (Overlay g1 g2) = Overlay (transpose g1) (transpose g2)
"transpose/Connect"  forall g1 g2. transpose (Connect g1 g2) = Connect (transpose g2) (transpose g1)

"transpose/overlays" forall xs. transpose (overlays xs) = overlays (map transpose xs)
"transpose/connects" forall xs. transpose (connects xs) = connects (reverse (map transpose xs))

"transpose/vertices" forall xs. transpose (vertices xs) = vertices xs
"transpose/clique"   forall xs. transpose (clique xs)   = clique (reverse xs)
 #-}

```

Note that the `transpose/vertices` and `transpose/clique` should ideally not be needed, since they are built using `overlays` and `connects`.

Sadly, the rules used in #103 seems to prevent the `transpose/overlays` to fire correctly in `star` once `vertices` gets inlined.

**Comment by snowleopard** [comment]
I think we can close this now. In the recent release, `transpose` is marked as a good consumer and `star` as a good producer, and we test these properties. This means they will properly fuse.

Thanks @nobrakal!
