### ISSUE TITLE
Restrictive upper bounds

### ISSUE THREAD

**Issue by jkachmar** [snowleopard/alga#118]
There's a restrictive upper bound on `base-orphans < 0.8` (the current version of `base-orphans`. 

Would it be possible to lift this bound to include `0.8` so that the package can be included in Stackage snapshots again?

**Comment by snowleopard** [comment]
@jkachmar Sure! Feel free to send a PR -- happy to merge if all CI bots pass.

**Comment by snowleopard** [comment]
Actually, never mind, I'll do it myself -- I'm preparing for a release anyway.

**Comment by snowleopard** [comment]
Done in #119.
