### ISSUE TITLE
Ord instance for graphs

### ISSUE THREAD

**Issue by snowleopard** [snowleopard/alga#126]
While playing with [QuickSpec](http://hackage.haskell.org/package/quickspec) to see if it can discover laws of algebraic graphs (yes, it can), I needed to add `Ord a => Ord (Graph a)` instance. My implementation simply redirected to the `Ord` of the `AdjacencyMap` representation, but I'm not sure if this is the best/most convenient way to define an ordering on graphs.

Any ideas how `Ord` should work?

**Comment by nobrakal** [comment]
The problem is that an `Ord` instance is required to satisfy:

```Haskell
x == y = compare x y == EQ
```

So I don't think that this is possible to implement a simple thing without `AdjacencyMap`, otherwise you will be able to implement graph equality.

The only problem I see with an `Ord` instance from `AdjacencyMap` is that its order not be very intuitive, because based on the order of the adjacency lists, itself based on the order of the vertices.

Hence we will have (in an `AdjacencyMap` context):

```Haskell
2*3 < 2 == False
2*3 < 3 == True
```

Or more generally,  the single vertex `a` will always be superior to any graph constructed with a least a vertex `<a`

**Comment by snowleopard** [comment]
@nobrakal One option is to insist that the `Ord` instance refines the `isSubgraphOf` relation. In other words:
* If ``x `isSubgraphOf` y`` then `x <= y`.
* As a consequence, this forces `Ord` to agree with the current `Eq` instance.

Note that this tells us that for your examples we have:

* `2 < 2*3 == True`
* `3 < 2*3 == True`

Which seems to be better.

But it leaves it open the following cases:

1. `1 < 2*3`
2. `4 < 2*3`
3. `1*2 < 2*3`
4. `2*2 < 2*3`
5. `3*4 < 2*3`

If we fall back to `AdjacencyMap`'s `Ord` instance after first checking `isSubgraphOf` then I think we will get the following:

1. `1 < 2*3 = True`
2. `4 < 2*3 = True`
3. `1*2 < 2*3 = True`
4. `2*2 < 2*3 = True`
5. `3*4 < 2*3 = False`

Not sure this is particularly intuitive...

**Comment by snowleopard** [comment]
I just had a chat with Victor Khomenko (@vkhomenko) and he suggested to use "size-lexicographical" orders on vertices and edges, as follows:

* Compare the size of graphs in terms of the number of vertices. In case of a tie continue.
* Compare the sets of vertices using the `Ord a => Ord (Set a)` order. In case of a tie continue.
* Compare the size of graphs in terms of the number of edges. In case of a tie continue.
* Compare the sets of edges using the `Ord a => Ord (Set (a, a))` order. 

I think this order refines the `isSubgraphOf` relation, and is a reasonable/convenient total order.

Here is a possible implementation:

```haskell
compare :: Ord a => Graph a -> Graph a -> Ordering
compare x y = vsize <> vset <> esize <> eset
  where
    vsize = compare (vertexCount x) (vertexCount y)
    vset  = compare (vertexSet   x) (vertexSet   y)
    esize = compare (edgeCount   x) (edgeCount   y)
    eset  = compare (edgeSet     x) (edgeSet     y)
```

Of course, we can optimise the above implementation quite a bit.

**Comment by nothingmuch** [comment]
it's also worth considering ordering for modular decomposition, as far as i know most algorithms start with an arbitrary vertex, so a total ordering on vertices or subgraphs would help modular decomposition produce a canonical form if i'm not mistaken

**Comment by snowleopard** [comment]
@nothingmuch Yes, modular decomposition is something that I'd like to implement at some point. In general, I think an Ord instance on graphs will be useful for many algorithms.

**Comment by snowleopard** [comment]
Done in #131.
