### ISSUE TITLE
Release versions in git?

### ISSUE THREAD

**Issue by subttle** [snowleopard/alga#127]
Hi all, thank you again for the wonderful work on this project! I have a minor comment. I noticed that there haven't been any releases under [releases](https://github.com/snowleopard/alga/releases) and I'm wondering if it would be any trouble to match the release versions with the versions listed on [hackage](http://hackage.haskell.org/package/algebraic-graphs). Or maybe there is a reason for not doing this? Thank you for your time.

**Comment by snowleopard** [comment]
@subttle Thank you! 

Indeed, I haven't been doing any GitHub releases, because that seemed unnecessary since one can always do `cabal get algebraic-graphs-0.2` to download the sources from Hackage.

Why would you like to have GitHub releases?

**Comment by subttle** [comment]
It's totally not necessary, it is just convenience and also I think it is the norm for many popular projects to keep track of the versions in git, for example [containers](https://github.com/haskell/containers/releases). Anyway, please close this if you are not partial to the idea, I won't be offended :)

**Comment by snowleopard** [comment]
@subttle The difficulty for me is just to remember to do the GitHub release every time :)

Let's keep the issue open: it will serve me as a reminder, plus other people might request GitHub releases too, and perhaps also share ways of automating this.

**Comment by snowleopard** [comment]
OK, here it is: https://github.com/snowleopard/alga/releases/tag/v0.3

Hope I won't forget next time :)

If I do, feel free to reopen!
