### ISSUE TITLE
Add Bifunctor instance for labelled graphs

### ISSUE THREAD

**Issue by boggle** [snowleopard/alga#156]
Labelled graphs are parameterized in both their node and edge type.

base has Bifunctor since 4.8
(http://hackage.haskell.org/package/base-4.12.0.0/docs/Data-Bifunctor.html)

Adding a Bifunctor instance would allow implementing `emap = Bifunctor.second`

**Comment by snowleopard** [comment]
@boggle Sounds good!

I'll have some time to implement this in January, but feel free to send a PR earlier.

**Comment by snowleopard** [comment]
Fixed in #162.
