### ISSUE TITLE
Add Dot/GraphViz generation

### ISSUE THREAD

**Issue by ndmitchell** [snowleopard/alga#16]
Everyone who has a graph wants to view it. Alga should provide some function that given a graph, and a way of labelling/styling the nodes, generates the appropriate DOT source.

**Comment by snowleopard** [comment]
Indeed, I also frequently miss this feature.

Adding a pretty-printer to DOT for graphs with `String`/`ByteString` vertices is straightforward, but I'm not sure what's the best approach to styling vertices. Do you have any suggestions?

Looking at https://en.wikipedia.org/wiki/DOT_(graph_description_language), a good start could be to handle `label` and `shape` vertex settings. We could give all control to the user as follows:

```haskell
-- All vertices must have a text label
-- Some vertices override the default shape setting
data DotStyle a = DotStyle { label :: a -> ByteString, shape :: a -> Maybe ByteString }

toDotWithStyle :: DotStyle a -> Graph a -> ByteString
toDotWithStyle s g = dotHeader s <> dotGraph s (edgeList g)
  where
    dotHeader = ...
    dotGraph  = ...

-- Default pretty-ptinter 
toDot :: Graph ByteString -> ByteString
toDot = toDotWithStyle (DotStyle id $ const Nothing)
```

Does this look sensible?

**Comment by ndmitchell** [comment]
I see you've jumped straight to a String type with no encoding - I suspect Text or String is more semantically correct (ignoring performance etc), as you may want non-ASCII characters.

Rather than have multiple functions for everything in DOT, why not have an `(a -> String)` which species the bit inside the `[...]`, and the people can use shape, label or whatever else they want. You could then also supply a helper `dotLabel x = "label=" ++ x`, so `toDot = toDotWithStyle dotLabel`.

**Comment by ndmitchell** [comment]
You could also imagine `dotAttributes :: [(String,String)] -> String` and then `dotLabel x = dotAttributes [("label", x)]`. I don't see much benefit from isolating people from DOT because it's both simple, and pretty leaky as an abstraction.

**Comment by snowleopard** [comment]
I like the idea of providing simple combinators like `dotLabel`. Indeed, we don't need to isolate users from DOT. Furthermore, this allows to support other file formats with the very same interface simply by providing more format-specific combinators.

To avoid deciding on the specific string type, we could use `OverloadedStrings`:

```haskell
-- We need to be able to create string literals and concatenate strings
type S a = (IsString a, Monoid a)

type DotAttributes a = S a => [a]

dotLabel :: S a => a -> DotAttributes a
dotLabel label = ["label=" <> label]

dotAttributes :: S a => DotAttributes a -> a
dotAttributes []     = ""
dotAttributes (a:as) = "[" <> a <> mconcat (map (" " <>) as) <> "]"

dotVertex :: S a => DotAttributes a -> a -> a
dotVertex [] vertex = vertex
dotVertex as vertex = vertex <> " " <> dotAttributes as
```

**Comment by ndmitchell** [comment]
Very neat idea regarding `S` - although I'd be tempted to expand it out in the few places that it's needed. Also no need to put the `S a` context in `DotAttributes` type alias - doing so makes things worse.

**Comment by snowleopard** [comment]
Agreed. Here is the next iteration:
```haskell
-- Keep DotAttributes abstract for better API robustness
newtype DotAttributes s = DotAttributes [s]

-- Allow users to combine attributes
instance Monoid (DotAttributes s) where ...

dotLabel :: (IsString s, Monoid s) => s -> DotAttributes s
dotLabel label = ["label=" <> label]

dotAttributes :: (IsString s, Monoid s) => DotAttributes s -> s
dotAttributes (DotAttributes [])     = ""
dotAttributes (DotAttributes (a:as)) = "[" <> a <> mconcat (map (" " <>) as) <> "]"

dotVertex :: (IsString s, Monoid s) => DotAttributes s -> s -> s
dotVertex (DotAttributes []) vertex = vertex
dotVertex attributes         vertex = vertex <> " " <> dotAttributes attributes
```

**Comment by ndmitchell** [comment]
None of those functions take a graph, but the basic shape is certainly there. Sounds good to me.

**Comment by snowleopard** [comment]
@ndmitchell After a bit of experimenting, here is what I came up with: 

https://gist.github.com/snowleopard/d0047a3298ce277ed4874c3dd25da6d0

Does this look reasonable?

P.S.: Graphviz renders the second example as:

![test2](https://user-images.githubusercontent.com/675286/28000197-256c8ec0-651c-11e7-952a-57e2dac462e5.png)

**Comment by ndmitchell** [comment]
Looks pretty cool. @pepeiborra might have some thoughts.

**Comment by pepeiborra** [comment]
Having written a less elegant version of this code recently, this is very welcome.

**Comment by snowleopard** [comment]
@ndmitchell @pepeiborra Great, thanks! I'll do the implementation over the weekend and will ask for some more feedback.

**Comment by snowleopard** [comment]
@ndmitchell @pepeiborra I've completed the implementation. Could you have a look?

* Module  `Algebra.Graph.Export.Dot` provides everything for exporting graphs in the DOT format:
https://github.com/snowleopard/alga/blob/master/src/Algebra/Graph/Export/Dot.hs

* Module `Algebra.Graph.Export` provides a few basic functions for generic graph export:
https://github.com/snowleopard/alga/blob/master/src/Algebra/Graph/Export.hs

**Comment by pepeiborra** [comment]
Looks good, we will use it.

**Comment by snowleopard** [comment]
@pepeiborra Thanks!

I think I'm done with tweaking the API. Will do the release soon.

**Comment by snowleopard** [comment]
Released: http://hackage.haskell.org/package/algebraic-graphs-0.0.5.
