### ISSUE TITLE
Improve support for undirected graphs

### ISSUE THREAD

**Issue by bolt12** [snowleopard/alga#170]
I read the paper and it's mentioned something about undirected graphs but I can't seem to reason about them using this library. I had to a naive implementation of a `undirectedConnect` function to get it rolling. I'm searching for some insight.

**Comment by snowleopard** [comment]
Indeed, we currently lack a proper support for undirected graphs. Here is what we do have:

* Module [`Algebra.Graph.Relation.Symmetric`](https://hackage.haskell.org/package/algebraic-graphs-0.3/docs/Algebra-Graph-Relation-Symmetric.html) which can be used for representing undirected graphs.
* Methods like [`symmetricClosure`](http://hackage.haskell.org/package/algebraic-graphs-0.3/docs/Algebra-Graph-AdjacencyMap.html#v:symmetricClosure) for turning all directed edges into a pair of edges going in both directions.

Is this sufficient for your purposes? If not, what kind of functionality are you missing?

Algebraically, undirected graphs differ from directed graphs only with one axiom: commutativity of `connect`, i.e. `connect x y = connect y x`.

**Comment by bolt12** [comment]
I see!

But how about a default behavior for `connect`? One that ensures that `edgesList (connect x y) == [(x,y), (y,x)]`

**Comment by snowleopard** [comment]
Well, the behaviour of `*` is already correct for `Algebra.Graph.Relation.Symmetric`:
```haskell
λ> import Algebra.Graph.Relation.Symmetric
λ> show (1 * 2 :: SymmetricRelation Int)
"edges [(1,2),(2,1)]"
```
Perhaps, what you are missing are a separate function `connect` and the instance `ToGraph`, so that you could use `edgeList`.

**Comment by bolt12** [comment]
Thanks I misunderstood, that's what I wanted!

**Comment by snowleopard** [comment]
Aha, thanks!

I've renamed the issue. I think we can still improve the support we provide for undirected graphs.

**Comment by bolt12** [comment]
Is there a way to use `Algebra.Graph.ToGraph` functions on `SymmetricRelation` without having to convert from/to `Relation` ? If I want to use `Algebra.Graph.ToGraph.vertexList` on a `SymmetricRelation` I have to convert it to `Relation` which has *Complexity: O(m*log(m)) time*

Maybe I'm structuring my imports the wrong way, but how can I use the `SymmetricRelation`type in a clean way? Should I use `Algebra.Graph.Class`? How?

**Comment by bolt12** [comment]
`SymmetricRelation` is not an instance of the `ToGraph`class.. I think that's what it would be needed to add in order to use `SymmetricRelation` smoothly. What do you think? Is implementing `ToGraph` a bad approach to your library?

**Comment by snowleopard** [comment]
> `SymmetricRelation` is not an instance of the `ToGraph`class.. I think that's what it would be needed to add in order to use `SymmetricRelation` smoothly. What do you think?

Yes, that's correct, and this is the right thing to do!

Feel free to send a PR adding a `ToGraph` instance for `SymmetricRelation`.

**Comment by bolt12** [comment]
Should I add `ToGraph`instance to `SymmetricRelation`or try and implement something similar to `Algebra.Graph.Relation` ? That way I wouldn't need to import the `ToGraph`module... but once again I dont know what would be the best approach

**Comment by snowleopard** [comment]
@bolt12 Yes, there is not a lot of functionality at the moment. You can compare undirected graphs, and you can `show` then. You can also list `neighbours` of a specific vertex. That's it.

Let me repeat my previous question: what kind of functionality are you missing?

You seem to have an application in mind, where you'd like to use undirected graphs, right? So, let's use your application as the guiding mechanism to figure out the kind of API you'd like to have. 

Imagine there is an abstract data type `Graph` which lives in the module `Algebra.Graph.Undirected`. Which functions would you like this module to provide? I guess there will be a large overlap with the API from `Algebra.Graph`, but still some functions will be different.

Let's not think about the actual implementation for now.

**Comment by bolt12** [comment]
I don't have any particular application in mind, i'm studying distributed systems in college and I'm studying undirected graphs, since DS can be modelled as ones, and learning to reason about them. I thought I'd use this library to mess around and get some excercises going.

I found odd that it's hard to use undirected graphs using this library and now I see that there's not a lot of functionality for them, and I'd be happy to help improve that!

What I'd like to see is maybe a data type `UndirectedGraph` that has all the functionalities as a `Graph` but respects the axiom `connect x y == connect y x` / `edgesList (1 * 2) == [(1,2),(2,1)]` . I like the library's approach to define an undirected graph as a symmetric relation and I don't know if it's easier to simply work with `SymmetricRelation`

> Imagine there is an abstract data type `Graph` which lives in the module `Algebra.Graph.Undirected`. Which functions would you like this module to provide? I guess there will be a large overlap with the API from `Algebra.Graph`, but still some functions will be different.

Besides the standard functions that exist on other implementations like `Graph` or `Relation` maybe would be nice to add functions to check if a graph is connected/simple/complete/etc.. ( I don't have any application in mind for these, but there might be algorithms that need them)

**Comment by snowleopard** [comment]
Great! I think you can start by extending the API of `SymmetricRelation` with a few simple functions, and if this goes well, you can go for more complicated algorithms, like connectivity checking.

Feel free to open a draft PR where we could discuss the actual code.

**Comment by bolt12** [comment]
Okay! I'll try to implement some of the already existing functions in `Relation`. Then I'll create the draft PR
