### ISSUE TITLE
Failing to install alga on ubuntu.

### ISSUE THREAD

**Issue by zengchu2** [snowleopard/alga#179]
I am running haskell on my Windows laptop with ubuntu. Here is the version of my "cabal" and "gch"
```
cabal-install version 1.22.6.0
using version 1.22.5.0 of the Cabal library
The Glorious Glasgow Haskell Compilation System, version 7.10.3
```
I tried to install alga using 
`cabal install alga` or `cabal install alga@next`
but failed and here is the error message. 
```
[ 3 of 13] Compiling Alga.Language.SyntaxTree ( src/Alga/Language/SyntaxTree.hs, dist/build/Alga/Language/SyntaxTree.o )

src/Alga/Language/SyntaxTree.hs:64:50:
    No instance for (Arbitrary GHC.Natural.Natural)
      arising from a use of ‘arbitrary’
    In the second argument of ‘(<$>)’, namely ‘arbitrary’
    In the expression: (% 1) . getNonNegative <$> arbitrary
    In an equation for ‘nonNegative’:
        nonNegative = (% 1) . getNonNegative <$> arbitrary
cabal: Error: some packages failed to install:
alga-0.2.2 failed during the building phase. The exception was:
ExitFailure 1
```
I managed to solve with the following commands. 
First pull the source code and change directory into it and call `cabal install` and the package is then installed successfully. 
Hope this can help anyone who get stucked with this problem. 
Should I use another version of cabal or ghc if I wanna to install the package using `cabal install alga`?

**Comment by snowleopard** [comment]
The Hackage package is called `algebraic-graphs`, not `alga`. This is because the name `alga` was already taken. So just use `cabal install algebraic-graphs`!

**Comment by zengchu2** [comment]
Thanks!

**Comment by snowleopard** [comment]
I guess we can close this then. 

@zengchu2 Don't hesitate to get in touch if you need any further help.
