### ISSUE TITLE
`induce` for filtering out edges

### ISSUE THREAD

**Issue by srid** [snowleopard/alga#182]
`induce` allows you to get a subgraph after filtering out specific `vertices`; but does it make sense to have one that allows filtering out `edges`?

I specifically have a property graph, with a use-case of traversing a sub-graph whose edges contain a particular property.

**Comment by snowleopard** [comment]
@srid Are you referring to edge-labelled graphs? If yes, then perhaps you could use `emap`:

https://hackage.haskell.org/package/algebraic-graphs-0.3/docs/Algebra-Graph-Labelled.html#v:emap

This function allows you to map over edge labels, so you can replace some labels by `zero`, effectively removing them from the graph.

If you are referring to graphs without edge labels, then do you mean something like this?

```haskell
removeEdges :: (a -> a -> Bool) -> Graph a -> Graph a
```

We don't have anything like this at the moment, but I can see how it can be useful.

**Comment by snowleopard** [comment]
P.S.: Note that the term "induced subgraph" is typically used in the context of removing vertices, not edges:

https://en.wikipedia.org/wiki/Induced_subgraph

**Comment by srid** [comment]
@snowleopard That's interesting; I didn't know about edge-labelled graphs in this library!

It comes close, but not close enough. What I have is a property graph, which would be *both* edge-labelled and vertex-labelled (`Graph v e a`). To efficiently implement I had to wrap the library's AdjacencyMap like this:

```haskell
data PropertyGraph' v vm em = PropertyGraph'
  (AdjacencyMap v)
  (Map v vm)
  (Map (v,v) em)
  deriving Generic

type PropertyGraph v vp ep = PropertyGraph' v (DMap vp Identity) (DMap ep Identity)
```

(I find [dependent-map](http://hackage.haskell.org/package/dependent-map) suitable for the label type as you can store variable number of typed properties).

Currently my filter function is obviously inefficient, something I'd optimize much later. It looks like this:

```haskell
subGraphWithEdge :: PropertyGraph -> EdgeProperty a -> G.AdjacencyMap Int
subGraphWithEdge pg@(PropertyGraph g _ _) ep =
  foldr (uncurry G.removeEdge) g otherEdges
  where
    otherEdges = filter (isNothing . getEdgeProperty pg ep) (G.edgeList g)
```

One difference between a `Graph v e a` and my `PropertyGraph' a v e` is that the later uses hash maps for efficient lookups of edges and labels.

I'll close this for now as filtering by edges does seem to exist via labelled graphs, but if you have any input on the above, that's be welcome!

**Comment by snowleopard** [comment]
@srid Interesting! I don't have anything more efficient in mind compared to your current implementation. If performance does become a problem for you in future, feel free to reopen this issue.
