### ISSUE TITLE
Acceptable Time complexity for `toAdjacecyMap`

### ISSUE THREAD

**Issue by adithyaov** [snowleopard/alga#195]
Hi, I was thinking about algorithms on the `Graph` structure defined in `Algebra.Graph` and noticed that it would be straightforward with the use of `toAdjacecyMap`. But as mentioned in the code itself `toAdjacencyMap` has an inefficient implementation.

What are the acceptable time and space complexities for `toAdjacencyMap`?

**Comment by snowleopard** [comment]
> What are the acceptable time and space complexities for `toAdjacencyMap`?

I don't think we can make it much faster than it currently is: it will still be at least O(n+m). If you have ideas of how to improve the current complexity, please share them! Anything that makes measurable improvements in the @nobrakal's benchmarking suite would be great.

Ideally, some functions, e.g. the equality check `==` would be implemented without using `toAdjacencyMap` at all, hopefully achieving O(s) time and memory complexity. I'd say this is our goal, but it may turn out to be difficult or impossible to achieve.

**Comment by adithyaov** [comment]
I'll close this for now as a solution might not exist. Hopefully, this issue will reopen, given some good ideas.
