### ISSUE TITLE
Functor instance for AdjacencyMap

### ISSUE THREAD

**Issue by michaelpj** [snowleopard/alga#201]
Seems like it should be fine to have one, any reason I'm missing why it wouldn't be?

It could probably have the `Applicative` and `Monad` instances similar to `Graph`, but I care about those less at the moment.

**Comment by snowleopard** [comment]
I don't think it's possible because of the required `Ord` constraints, e.g. see `gmap`:

https://hackage.haskell.org/package/algebraic-graphs-0.4/docs/Algebra-Graph-AdjacencyMap.html#v:gmap

We might be able to work around this with various approaches invented for making a `Functor Set` instance, but I'm not sure if it would be really that useful. Would it?

**Comment by michaelpj** [comment]
Ah rats of course, we're using `Set` for the adjacent vertices.

We could weaken the internal representation to a list of adjacent vertices. I don't know how much that costs us - we might potentially have duplicates, but that seems relatively unlikely. And then we can just convert to `Set` in any places in the API that want it.

It's a shame, having `Functor` is very useful.

**Comment by snowleopard** [comment]
I don't think it's just about adjacent vertices: we use `Map a (Set a)`, and `Map` is not a `Functor` on keys.

**Comment by michaelpj** [comment]
Gotcha. So we'd have to devolve all the way to adjacency lists, which have much worse asymptotics.

**Comment by snowleopard** [comment]
You could try the `Coyoneda` trick, i.e. work with `Coyoneda AdjacencyMap a`:

https://hackage.haskell.org/package/kan-extensions-5.2/docs/Data-Functor-Coyoneda.html

Not exactly sure it will work for you, but curious to hear your thoughts :)

**Comment by michaelpj** [comment]
I don't think that helps me much - you have to have a functor to get back out again, and it's not much more convenient than just using `gmap`.

Plus the `Functor` instance lets you implement other instances.

**Comment by snowleopard** [comment]
Yep, I see. Well, I guess this means we need more efficient algorithms for algebraic graphs, which are proper functors, etc.!
