### ISSUE TITLE
Add induceJust

### ISSUE THREAD

**Issue by michaelpj** [snowleopard/alga#202]
From http://hackage.haskell.org/package/witherable-0.3

Given that we can't currently have a graph with a separate key type (https://github.com/snowleopard/alga/issues/141), I'm constructing a graph of keys, and then I want to map over the graph looking up the value of the key, to get a graph of values.

However, lookup is naturally `a -> Maybe b`, an so even with a `Functor` instance (https://github.com/snowleopard/alga/issues/201) I'd still have a `Graph (Maybe value)`.

Having `filter`/`mapMaybe`/`catMaybes` seems like an fine solution. We could either add them as simple functions or use the `Filterable` class.

**Comment by snowleopard** [comment]
Like `Functor AdjacencyMap`, this has the problem of relying on `Ord` constraints.

What we could do is to have a type-safe version of `induce`, like this:

```haskell
induceJust :: Ord a => AdjacencyMap (Maybe a) -> AdjacencyMap a
```

Will that work for you?

**Comment by michaelpj** [comment]
That would certainly work!

**Comment by michaelpj** [comment]
Also, I've realised that I can work with `Graph` and then only convert to `AdjacencyMap` later. So `instance Filterable Graph` would also do for me. At this point it's mostly a question of whether you want to use the class as part of the API or not.

**Comment by michaelpj** [comment]
Er no, scratch that, I need to do my SCC computation before I map and induce, so I do care about `AdjacencyMap`.

**Comment by snowleopard** [comment]
@michaelpj Great, I'll try to add `induceJust` soon. 

Regarding `Filterable`: I'd prefer to stay light on dependencies, so let's stick to `induceJust` for now.

**Comment by Avasil** [comment]
Is it still relevant? I could try contributing it if nobody is working on it

**Comment by snowleopard** [comment]
@Avasil Yes, it's still relevant! Please go ahead :)

**Comment by snowleopard** [comment]
@michaelpj Thanks to @Avasil, we now have `induceJust` and `induceJust1` for non-empty graphs, to be released soon.

**Comment by michaelpj** [comment]
Thanks!
