### ISSUE TITLE
Hackage Release

### ISSUE THREAD

**Issue by fosskers** [snowleopard/alga#251]
Hi there, I've confirmed that the `master` branch of `algebraic-graphs` works just fine with `nightly-2020-01-21` (GHC 8.8.1). However, `0.4` as released on Hackage no longer does.

Would it be possible to upload a `0.4.1` that includes the latest tweaks and [bounds fixes](https://github.com/snowleopard/alga/pull/238)? Thank you.

**Comment by snowleopard** [comment]
@fosskers Hi there! I actually plan to release 0.5 pretty soon -- most likely during the upcoming week. Will that be OK?

**Comment by fosskers** [comment]
Sure, that works. Thank you!

**Comment by snowleopard** [comment]
Great, will do!

**Comment by snowleopard** [comment]
Released: http://hackage.haskell.org/package/algebraic-graphs-0.5!

**Comment by fosskers** [comment]
Wonderful, thank you!
