### ISSUE TITLE
How to handle goodness inherited from other libraries

### ISSUE THREAD

**Issue by nobrakal** [snowleopard/alga#252]
Hi,

I just discovered that [`Data.Set.toAscList`](http://hackage.haskell.org/package/containers-0.6.2.1/docs/Data-Set.html#v:toAscList) is subject to list fusion. This makes, for example, `Data.Graph.vertexList` automatically a good producer of lists.

The right path to follow seems not clear, should we:

1. Only document this
2. Document and test, that is, testing some functions from another library
3. Keep it for us (I don't think this is a good choice, but I added it to be exhaustive)

?

(I think there is a more conceptual issue on how goodness is actually handled in general, but this is out of scope)

**Comment by snowleopard** [comment]
@nobrakal I am inclined to document and test this, i.e. go with option (2), because `containers` is a very stable library and it is safe to assume that `Data.Set.toAscList` will remain a good producer in the foreseeable future.

> (I think there is a more conceptual issue on how goodness is actually handled in general, but this is out of scope)

(Is there some kind of `Goodness` monad to be discovered? :-))

**Comment by nobrakal** [comment]
@snowleopard Ok, you convinced me, I will try to submit a PR during the week !

> Is there some kind of Goodness monad to be discovered?

I don't know yet, but I am working on it :D
