### ISSUE TITLE
Bump upper bound for base-compat for version 0.4 on Hackage

### ISSUE THREAD

**Issue by adamse** [snowleopard/alga#253]
I tried locally editing the cabal file to allow base-compat-11.0 and it built fine.

**Comment by snowleopard** [comment]
@adamse Do you mind waiting a few days until version 0.5? It will have no `base-compat` dependency at all.

**Comment by adamse** [comment]
That's fine by me! (I've already done the bump locally for my purposes.) 👍

**Comment by snowleopard** [comment]
Great! I'll close the issue after the release.

**Comment by snowleopard** [comment]
Released: http://hackage.haskell.org/package/algebraic-graphs-0.5!
