### ISSUE TITLE
Unable to use ghcid

### ISSUE THREAD

**Issue by srid** [snowleopard/alga#260]
Full build (nix-build) succeeds, but I can't use ghcid for some reason.

![image](https://user-images.githubusercontent.com/3998/80660392-8a958a80-8a59-11ea-996c-72369caa7988.png)

**Comment by snowleopard** [comment]
I'm not using Nix, and can't reproduce with my setup.

Note that `DeriveFunctor` is in the `default-extensions` in the `common` stanza. Perhaps, you are using an old Cabal that doesn't support `common` stanzas?

**Comment by andrewthad** [comment]
The problem is almost certainly the use of `default-extensions`. If ghcid is just invoking ghci (rather than cabal repl), then the expecting extensions will not be enabled, and compilation will fail. The solution is simple: put `{-# language DeriveFunctor #-}` at the top of every module instead of using `default-extensions`.

**Comment by snowleopard** [comment]
@andrewthad Default extensions can also be enabled in the `.ghci` script, as I'm doing here:

https://github.com/snowleopard/alga/blob/f3382596498a69d8ebce1e0ccb36dd99e9ae3810/.ghci#L7-L12

Perhaps, it's just a matter of adding `DeriveFunctor` there? I'd be happy to accept a PR that does that if it fixes this issue for you.

**Comment by andrewthad** [comment]
I suspect that would fix it too. I don't use nix though, so I cannot replicate the OP's issue.

**Comment by wbadart** [comment]
@srid can you share the derivation you're using?

**Comment by srid** [comment]
I don't remember right now, but I believe I was using alga as an [obelisk thunk](https://github.com/obsidiansystems/obelisk/blob/master/FAQ.md) in a GHC 8.6 project. 

I'll close this as I'm not looking for a solution to this anymore, but feel free to open if anybody thinks this is worth supporting.
