### ISSUE TITLE
Support older GHC.

### ISSUE THREAD

**Issue by phadej** [snowleopard/alga#27]
I can make a PR for this is well.

It would be great to support GHC >= 7.6 (7.4 would need older containers-0.4)
Then I could ask people to add dependency on alga.

with https://github.com/hvr/multi-ghc-travis it would be easy to test them all on Travis (even OSX, if you really insist, though for `alga` it's IMHO waste of scarse OSX travis resources)

**Comment by snowleopard** [comment]
@phadej Thank you! I've never worked on Haskell projects with long-term GHC compatibility requirements, so let me ask a couple of naive questions:
* Your PR #28 gives a working solution for GHC 7.8, which means supporting the current version of GHC 8.2.1, plus three previous versions. Is this a common compatibility target? Would supporting even older versions be useful, e.g. are there a lot of users of GHC 7.6?
* What is the long term plan for Alga with new versions of GHC coming out? Say, GHC 8.4 is out -- do we then discontinue support for GHC 7.8, or will we keep accumulating CPP and other compatibility hacks? 

> Then I could ask people to add dependency on alga.

Are you referring to a particular project you work on? I'm curious! (And a bit worried, since Alga's API is still not very polished and stable.)

> even OSX, if you really insist, though for alga it's IMHO waste of scarse OSX travis resources

I think it would be nice to run Travis OSX with the latest GHC version. Just in case.

**Comment by phadej** [comment]
There are three strategies:
- Support as many GHC as is convenient. This is subjective measure, but it means, that if you would like to use say `TypeInType` or `TypeApplications`, then you'll require at least GHC-8.0.
    - This is common with libraries which heavily rely on some GHC features.
    - type-leval `Nat` and `Symbol` didn't exist before GHC-7.8
    - When GHC-8.4 is released, you won't do anything, except if "it's time to clean-up stuff a little"
- Support three latest GHC (three because of https://prime.haskell.org/wiki/Libraries/3-Release-Policy)
    - that means that supporting GHC-7.8 isn't required anymore.
    - When GHC-8.4 is released, you can drop GHC-7.10 support, etc.
- Support as many as you can. This is hard-core, and I don't propose it for `alga`. That's semi required e.g. for testing / benchmarking libs etc.
    - This is a variation of the first strategy.
        - there "I want `TypeApplications`", I use them
        - here, "I want `TypeApplications`", I rethink, do I really need them.
    - Though there is little reason to support older compilers than GHC-7.4 atm.
    - And e.g. [Matrix CI](https://matrix.hackage.haskell.org/package/algebraic-graphs) doesn't test for older GHC atm.

So my GHC-7.8 PR is something in between *convenient* and *3-release-policy*. I tried GHC-7.6, and it starts to be a little inconvient (I didn't think too hard about the test-suite issue). With `base-compat`, AMP is almost no-issue (I had to add single CPP). I think that `base-compat` (and `base-orphans`) are useful in general anyway, see their changelogs
- http://hackage.haskell.org/package/base-compat-0.9.3/changelog
- http://hackage.haskell.org/package/base-orphans-0.6/changelog

I know that I'm a minority, but I often check how package's matrix page looks like. Multiple GHC version support tells *this package could have been there 5 years ago already, so probably will work 5 next years as well* :) e.g. 
- https://matrix.hackage.haskell.org/package/lens

---

I work on Cabal/Hackage stuff, and I'd might start using `algebraic-graphs` for dependency graph stuff, it's either `fgl` or `alga`. I don't really know for what, as soon as I do something else than just printing the graph, I'll ping you :)

---

about OSX, well, I tried to postpone the OSX stuff for as latest as possible, but I'll take a look in the generator.

**Comment by phadej** [comment]
FWIW, it might be good idea to mention somewhere that `algebraic-graphs` is quite light on GHC extensions, `RankNTypes` and `TypeFamilies`.

That's what me got to think that supporting older GHC should be too complicated.

**Comment by snowleopard** [comment]
Thank you very much for such a detailed response! Let's go with your intermediate GHC-7.8 solution.

> I don't really know for what, as soon as I do something else than just printing the graph, I'll ping you :)

Awesome! Lots of things are missing here at the moment, but I'm happy to add new features.

> FWIW, it might be good idea to mention somewhere that `algebraic-graphs` is quite light on GHC extensions, `RankNTypes` and `TypeFamilies`.

Indeed, and the very core is actually quite small. I'd say, `data Graph` is sufficient for most purposes, so it's possible to create a lighter library that doesn't require `RankNTypes` and `TypeFamilies`.

**Comment by snowleopard** [comment]
A couple of TODO's (I'll try to take care of them today):
- [ ] Add OS X CI (to test only with the latest GHC version).
- [ ] Try to get rid of the dependency on `semigroups`, see https://github.com/snowleopard/alga/pull/28#discussion_r150408623.

**Comment by snowleopard** [comment]
OK, I think this can now be closed. Thanks @phadej!
