### ISSUE TITLE
support for GraphViz "HTML strings" for node or edge labels

### ISSUE THREAD

**Issue by jmtd** [snowleopard/alga#272]
Hello!

GraphViz supports something called [HTML-like labels](https://graphviz.org/doc/info/shapes.html#html) for some objects. This can be useful for adding some mark-up to edge or node labels (e.g. fractions with `<<SUP>1</SUP>/<SUB>2</SUB>2>`). A HTML-like label is delimited with a pair of angle brackets instead of double-quotes. E.g.

```
digraph {
  1 [label="regular label"];
  2 [label=<<B>emboldened label</B>>];
  1 -> 2;
}
```

resulting in:

![tmp](https://user-images.githubusercontent.com/63694/128383085-78d2d6eb-bba7-4b6d-a749-5664fa394b49.png)

[The current handling of attributes in Algebra.Graph.Export.Dot](https://github.com/snowleopard/alga/blob/master/src/Algebra/Graph/Export/Dot.hs#L127) always wraps labels in double-quotes. It would be nice to be able to specify that the HTML-like format was to be used. 

(I completely forgot about #44/#47 in the intervening years. I'll try to pick it back up)

**Comment by snowleopard** [comment]
@jmtd Hi there! Perhaps, we can make it possible to disable double-quoting by adding a new field to `Style`, e.g. called `quoting` with choices `None` and `Double` (with the latter being the default)?

> (I completely forgot about #44/#47 in the intervening years. I'll try to pick it back up)

Yep, it would be great to finally merge #47!
