### ISSUE TITLE
v0.6 fails to build with GHC 8.0 and 8.2

### ISSUE THREAD

**Issue by sjakobi** [snowleopard/alga#284]
See https://matrix.hackage.haskell.org/#/package/algebraic-graphs.

Since dropping support for these GHC versions seems intentional (https://github.com/snowleopard/alga/pull/278), I suggest that you require `base >= 4.11`.

v0.6 should be revised with the same bounds.

**Comment by snowleopard** [comment]
Sounds good, thanks for catching this! Will do in the next couple of days.

I'm not very familiar with Hackage revisions. Is it OK if I simply release `v0.6.0.1`?

**Comment by sjakobi** [comment]
Releasing a v0.6.0.1 with fixed bounds wouldn't be sufficient unless you also deprecate v0.6. The reason is that build tools with dependency solvers will still attempt to use v0.6 with GHC 8.0 and 8.2.

Publishing a new version for this issue would also be a bit wasteful with the size of the package index.

So I'd recommend addressing this with a Hackage revision. If you do this via the web interface (click "edit package information", then click "algebraic-graphs-0.6" in the "Cabal file metadata" section), you can review the changes before publishing them via the "Review changes" button. If you end up making an unintended change, you can fix it with a second revision.

Alternatively I can perform the revision for you – as a Hackage trustee I have the necessary permissions.

**Comment by snowleopard** [comment]
Thanks for the instructions! Everything seems to have worked out well. Feel free to reopen if I messed anything up.
