### ISSUE TITLE
Algebra.Graph.Labelled.AdjacencyMap.edges appears to be broken

### ISSUE THREAD

**Issue by bgamari** [snowleopard/alga#301]
`AdjacencyMap.edges` appears not to introduce any edges:
```
λ> import Algebra.Graph.Labelled.AdjacencyMap
λ> a = AdjMap.edges [((), 'a','b')]
λ> AdjMap.edgeList a
[]
λ> AdjMap.adjacencyMap a
fromList [('a',fromList []),('b',fromList [])]
```

**Comment by bgamari** [comment]
Ahh, never mind; I now see that "zero" edges are trimmed from the graph.

**Comment by snowleopard** [comment]
Yeah, I guess the case with `e = ()` can be pretty confusing since it yields a set rather than a graph.
