### ISSUE TITLE
Non empty graphs

### ISSUE THREAD

**Issue by snowleopard** [snowleopard/alga#31]
@phadej makes a very good observation in #24: Alga currently does not provide any support for type-safe handling of non-empty graphs.

I also wanted `NonEmptyGraph` a few times. Many graph transformations become much simpler when graph expressions cannot contain the `Empty` leaf. (And conversely, many graph transformations become simpler when `Empty` leafs are allowed, so general graphs are also useful -- we need both.)

The algebraic data type for non-empty graphs is straightforward:
```haskell
data NonEmptyGraph a = Vertex a
                     | Overlay (NonEmptyGraph a) (NonEmptyGraph a)
                     | Connect (NonEmptyGraph a) (NonEmptyGraph a)
```

However, there are a couple of design questions that need to be answered:
* Where should non-empty graphs live? I suggest a separate module `Algebra.Graph.NonEmpty`. This will lead to quite a bit of code/docs/tests duplication, but I don't see a better way. Incidentally, this is what happens with the standard `Data.List.NonEmpty`, which has quite a bit of overlap with `Data.List`.
* Do we also create a type class for non-empty graphs (or plexes, or whatever else we are going to name the general concept of things with overlay and connect operations, see #24)? If yes, and if we stick to the current naming where we have `class Graph g`, we'll then add `class NonEmptyGraph g` that will be the superclass of `class Graph g`.
* What do we do with `Relation`, `AdjacencyMap`, etc.? Do we need their non-empty versions? I think the answer is No, but I'm not sure.

Thoughts?

**Comment by snowleopard** [comment]
Perhaps, a slightly better approach would be to stick to the name `Graph`, but use module names to distinguish between general and non-empty graphs?

More specifically:
```haskell
module Algebra.Graph.NonEmpty (Graph (..)) where

data Graph a = Vertex a
                     | Overlay (Graph a) (Graph a)
                     | Connect (Graph a) (Graph a)
```

Now, if one would like to be explicit about the data type, it's possible to write `NonEmpty.Graph`. And if non-empty graphs are assumed throughout the codebase, then a simple `Graph` will work.

This is similar to `Data.Map.Strict` and `Data.Map.Lazy` that both definine data type `Map`.

Following this approach we can also have `Undirected.Graph`, `Reflexive.Graph`, `Undirected.NonEmpty.Graph` etc. without the need to invent longer and longer names for various graph data-types.

**Comment by phadej** [comment]
A side note, `Data.Map.Strict.Map` and `Data.Map.Lazy.Map` are the same datatype! (only functions differ).

I'd prefer to have different names for the types, as the functions will be the same, thanks to the type class machinery,

**Comment by snowleopard** [comment]
Done!

@phadej Thanks for the suggestion and let me know if you spot any issues with the implementation.

I decided not to add a type class for non-empty graphs for now. I think it deserves a new issue.
