### ISSUE TITLE
Bump "deepseq" dependency bounds to 1.5.0.0 

### ISSUE THREAD

**Issue by danidiaz** [snowleopard/alga#310]
There's a new version of deepseq: https://hackage.haskell.org/package/deepseq-1.5.0.0

**Comment by danidiaz** [comment]
Oops, I see that it has already been bumped in the code. https://github.com/snowleopard/alga/blob/aee5fa79a1ce53861c9a9bb770309dbf68a1bc9a/algebraic-graphs.cabal#L73

Perhaps it would be worth it to change the Hackage metadata for alga 0.7 as well?

**Comment by snowleopard** [comment]
Done, see the latest revision: https://hackage.haskell.org/package/algebraic-graphs-0.7/revisions/
