### ISSUE TITLE
Bring the Todo example back

### ISSUE THREAD

**Issue by snowleopard** [snowleopard/alga#51]
It was a good example: https://blogs.ncl.ac.uk/andreymokhov/graphs-in-disguise/

We should adapt it to the current implementation of the library and bring back to the repository, for example, as `Algebra.Graph.Example.Todo`.

**Comment by snowleopard** [comment]
And an older version is still available in the history of this repo: 

https://github.com/snowleopard/alga/blob/91b97ce5c4cad5bd89cf7aae8eebad0c4ba88e1d/src/Algebra/Graph/Todo.hs

**Comment by faezs** [comment]
Hi @snowleopard. Just getting started exploring the library and this seems like a great acclimatizing task for me to take on. Would you mind a haskell newbie giving this a shot?

**Comment by snowleopard** [comment]
@faezs Sure, feel free to give it a try and send a PR. Thank you!

**Comment by chenzizhao** [comment]
Hey all, it seems to have been a while. I was just having fun with Haskell and picked this up. Feedback appreciated!
