### ISSUE TITLE
Publishing alga

### ISSUE THREAD

**Issue by adelbertc** [snowleopard/alga#6]
Hey,

Awesome work with this project, really interesting stuff. I had done lots of graph theory stuff in the past and am thinking about getting back into it. I'm looking to potentially build some stuff on top of `alga` and was wondering if you have any plans on publishing it soon?

On a related note it does look like there's already an `alga` on Hackage: https://hackage.haskell.org/package/alga

Thanks!

**Comment by snowleopard** [comment]
Hey @adelbertc!

I'm currently preparing the library for Hackage (writing docs, refactoring the module structure, etc.) and aim to release it very soon.

Indeed, the name is already taken, which is unfortunate. I think I'll release the library as `alga-core`. It will be lightweight and will have minimal dependencies. More heavyweight stuff (e.g. algorithms operating on algebraic graphs that may potentially pull in dependencies such as `fgl`) will go into a separate library.

**Comment by adelbertc** [comment]
Awesome, looking forward to it! If I end up writing some stuff on top of `alga` I'll be sure to let you know :-)

**Comment by l-d-s** [comment]
I suggest a name that more directly evokes graphs might be more salient.

Very much looking forward to the maturation of this library.

**Comment by ndmitchell** [comment]
While I think alga is a perfectly fine name, if foo  exists on hackage, calling your library foo-core is probably a bad idea. That name is gone - time to think of a new one...

**Comment by ndmitchell** [comment]
On the other hand, graph-core wouldn't be so bad since graph is not a "named" library as such being too generic.

**Comment by snowleopard** [comment]
@l-d-s @ndmitchell I don't think I explained this anywhere before: "alga" is a sort of acronym for "algebraic graphs", which also means "go!" or "come on!" in Kyrgyz language -- a little hidden tribute to my home country :-)

As far as I understand, we could use `Alga` (capitalised) on Hackage. Would this be confusing?

A more verbose name, but very precise is `algebraic-graphs`. I think if we don't go the `alga` way, this is my current preference.

@ndmitchell Yep, `graph-core` is also an option. It may be still too generic though.

**Comment by ndmitchell** [comment]
Alga is an awesome name, but it is unfortunately taken. Using `Alga` does work according to the rules of Hackage, but is confusing and generally packages are expected to be `lower-kebab-case` - I wouldn't recommend it (if the existing package was `Alga` and not heavily used you could just about get away with it).

`algebraic-graphs` seems good.

**Comment by adelbertc** [comment]
👍 to `algebraic-graphs`

**Comment by snowleopard** [comment]
OK, the above commit switched the package name to `algebraic-graphs`.

We can still refer to the project/library as Alga, for brevity :)

**Comment by snowleopard** [comment]
The library has been released on Hackage: http://hackage.haskell.org/package/algebraic-graphs and is on the way to Stackage.

It's got 100% documentation coverage, and close to 100% test coverage.

🎉
