### ISSUE TITLE
Specialize functions using Set with IntSet when possible

### ISSUE THREAD

**Issue by nobrakal** [snowleopard/alga#75]
I was reading GHC options, and one can use `RULES` [to use specialized functions when needed](https://downloads.haskell.org/~ghc/latest/docs/html/users_guide/glasgow_exts.html#rule-spec).

Because `Graph Int` is a common type, I think that providing some specialized functions can be a good idea.

The specialisation will look like
```Haskell
vertexList :: Ord a => Graph a -> [a]
vertexList = Set.toAscList . vertexSet
{-# INLINE[1] vertexList #-}

{-# RULES "vertexList/Int" vertexList = vertexIntList #-}
vertexIntList :: Graph Int -> [Int]
vertexIntList = IntSet.toAscList . vertexIntSet

```

Particularly for `vertexList` and `vertexCount`.

Some bench on `vertexCount` using `Graph Int`:

## vertexCount

Descritpion: Count the vertices of the graph

### Mesh
<TABLE>
   <TR>
      <TH>
      </TH>
      <TH CLASS = "thinright">
         1
      </TH>
      <TH CLASS = "thinright">
         10
      </TH>
      <TH CLASS = "thinright">
         100
      </TH>
      <TH>
         1000
      </TH>
   </TR>
   <TR>
      <TH>
         Alga
      </TH>
      <TD CLASS = "thinright">
         32.81 ns
      </TD>
      <TD CLASS = "thinright">
         498.9 ns
      </TD>
      <TD CLASS = "thinright">
         9.443 μs
      </TD>
      <TD>
         155.5 μs
      </TD>
   </TR>
   <TR>
      <TH>
         AlgaOld
      </TH>
      <TD CLASS = "thinright">
         29.64 ns
      </TD>
      <TD CLASS = "thinright">
         4.620 μs
      </TD>
      <TD CLASS = "thinright">
         118.0 μs
      </TD>
      <TD>
         2.045 ms
      </TD>
   </TR>
</TABLE>

### Clique
<TABLE>
   <TR>
      <TH>
      </TH>
      <TH CLASS = "thinright">
         1
      </TH>
      <TH CLASS = "thinright">
         10
      </TH>
      <TH CLASS = "thinright">
         100
      </TH>
      <TH>
         1000
      </TH>
   </TR>
   <TR>
      <TH>
         Alga
      </TH>
      <TD CLASS = "thinright">
         32.63 ns
      </TD>
      <TD CLASS = "thinright">
         1.657 μs
      </TD>
      <TD CLASS = "thinright">
         371.9 μs
      </TD>
      <TD>
         82.46 ms
      </TD>
   </TR>
   <TR>
      <TH>
         AlgaOld
      </TH>
      <TD CLASS = "thinright">
         29.84 ns
      </TD>
      <TD CLASS = "thinright">
         15.87 μs
      </TD>
      <TD CLASS = "thinright">
         3.838 ms
      </TD>
      <TD>
         585.7 ms
      </TD>
   </TR>
</TABLE>

SUMMARY:

 * Alga was the fastest 6 times
 * AlgaOld was the fastest 1 times
There was 1 ex-aequo

ABSTRACT:

 * Alga was 2.85 times faster than AlgaOld

**Comment by snowleopard** [comment]
@nobrakal Great idea! Let's do that once I complete the refactoring in #74.

**Comment by nobrakal** [comment]
I don't know if it worth using [Specialize pragma](https://downloads.haskell.org/~ghc/latest/docs/html/users_guide/glasgow_exts.html#specialize-pragma)

It generate a copy of the function but only specialized for `Int` and thus avoid the type parameter in Core

**Comment by snowleopard** [comment]
@nobrakal I'm not sure what you mean. I guess this only helps to optimise type classes -- for example, you could use it to specialise code for some known `ToGraph` instances. Or, similarly, for the type classes `Graph`.

**Comment by nobrakal** [comment]
Using this SPECIALIZE pragmatic will duplicate functions where used, simply replacing their generic type `a` by `Int` and make them faster for `Graph Int` object (because generic functions have to carry a type argument once represented in SystemF)

**Comment by snowleopard** [comment]
I see. Can you try if this gives a good performance boost to some existing function?

**Comment by nobrakal** [comment]
Well I haven't tested, but it give actually a nice speedup. For example, after adding a SPECIALIZE instruction for Graph Int on `induce`, `foldg` and `hasEdge`, I have

## hasEdge

Descritpion: Test if the given edge is in the graph (with arguments both in the graph and not in the graph (where applicable))

### Mesh
<TABLE>
   <TR>
      <TH>
      </TH>
      <TH CLASS = "thinright">
         1
      </TH>
      <TH CLASS = "thinright">
         10
      </TH>
      <TH CLASS = "thinright">
         100
      </TH>
      <TH>
         1000
      </TH>
   </TR>
   <TR>
      <TH>
         Alga
      </TH>
      <TD CLASS = "thinright">
         328.9 ns
      </TD>
      <TD CLASS = "thinright">
         1.352 μs
      </TD>
      <TD CLASS = "thinright">
         1.341 μs
      </TD>
      <TD>
         2.220 μs
      </TD>
   </TR>
   <TR>
      <TH>
         AlgaOld
      </TH>
      <TD CLASS = "thinright">
         583.9 ns
      </TD>
      <TD CLASS = "thinright">
         2.363 μs
      </TD>
      <TD CLASS = "thinright">
         2.351 μs
      </TD>
      <TD>
         3.364 μs
      </TD>
   </TR>
</TABLE>

### Clique
<TABLE>
   <TR>
      <TH>
      </TH>
      <TH CLASS = "thinright">
         1
      </TH>
      <TH CLASS = "thinright">
         10
      </TH>
      <TH CLASS = "thinright">
         100
      </TH>
      <TH>
         1000
      </TH>
   </TR>
   <TR>
      <TH>
         Alga
      </TH>
      <TD CLASS = "thinright">
         330.3 ns
      </TD>
      <TD CLASS = "thinright">
         6.195 μs
      </TD>
      <TD CLASS = "thinright">
         558.4 μs
      </TD>
      <TD>
         92.89 ms
      </TD>
   </TR>
   <TR>
      <TH>
         AlgaOld
      </TH>
      <TD CLASS = "thinright">
         580.1 ns
      </TD>
      <TD CLASS = "thinright">
         8.043 μs
      </TD>
      <TD CLASS = "thinright">
         622.8 μs
      </TD>
      <TD>
         101.5 ms
      </TD>
   </TR>
</TABLE>


SUMMARY:

 * Alga was the fastest 23 times
There was 1 ex-aequo


ABSTRACT:
(Based on an average of the ratio between largest benchmarks)

 * Alga was 1.32 times faster than AlgaOld

It can I think boost `hasVertex` and `isEmpty`.

But I don't know if it worth adding this to other functions. In fact I don't know the counterpart of specializing a whole library ^^

**Comment by snowleopard** [comment]
@nobrakal Thanks! The benefit seems to be significant. 

I think we should go for it. The only downside is that the resulting binaries are going to be bigger (we generate more specialised code), but that's probably not a big deal. 

We can even try to measure the effect on the size of binaries -- compare the size of an executable with and without the specialisation. I doubt the impact will be that big.

**Comment by nobrakal** [comment]
Mhh I misunderstood how worked SPECIALIZE. This article explain it better than me : http://mpickering.github.io/posts/2017-03-20-inlining-and-specialisation.html

It works only for _overloaded_ functions. (I optimized `hasEdge` by change, since it requires an `Ord` instance ^^ ).

So I agree that specializing overloaded functions of alga won't cost too much !

**Comment by nobrakal** [comment]
I think this can be closed now, I don't see further optimization concerning specialization for `Algebra.Graph`

**Comment by snowleopard** [comment]
@nobrakal Many thanks for exploring this! I think we got a good speed up thanks to specialisation.
