### ISSUE TITLE
Foldable instance for Data.Graph

### ISSUE THREAD

**Issue by snowleopard** [snowleopard/alga#8]
I can't decide whether we need to make `Data.Graph` an instance of `Foldable` or not.

On the one hand, just by `deriving Foldable` we get useful methods like `toList`, `length`, `elem`, which have a sensible behaviour on `Data.Graph` expressions.

On the other hand, methods like `foldMap` and `fold` are quite confusing, because we'd like to define graph folds differently. 

For example, here is a generalised graph fold `foldg`:
```haskell
foldg :: b -> (a -> b) -> (b -> b -> b) -> (b -> b -> b) -> Graph a -> b
foldg e v o c = go
  where
    go Empty         = e
    go (Vertex x)    = v x
    go (Overlay x y) = o (go x) (go y)
    go (Connect x y) = c (go x) (go y)
```

It's very useful, because we can implement a lot of functions using it:
```haskell
g >>= f = foldg Empty f             Overlay Connect g
toList  = foldg []    return        (++)    (++)
size    = foldg 0     (const 1)     (+)     (+)
isEmpty = foldg True  (const False) (&&)    (&&)
```

We also have `fold` which is currently defined as:
```haskell
fold :: Class.Graph g => Graph (Vertex g) -> g
fold = foldg empty vertex overlay connect
```
Note that `fold` could probably be renamed to `fromGraph`, as suggested in #5.

What do you think: shall we derive `Foldable`? If yes, do we also derive `Traversable`?

**Comment by ndmitchell** [comment]
Yes, derive Foldable and Traversable. You certainly want a fold, but you don't have to name it fold - foldGraph is absolutely fine.

**Comment by snowleopard** [comment]
@ndmitchell Thanks, done!
