### ISSUE TITLE
Implement Algebra.Graph.Undirected

### ISSUE THREAD

**Issue by adicirstei** [snowleopard/alga#83]
Hi,

I have a dumb question. At first I thought that a `SymmetricRelation` being a `Graph` and a `Graph` being a `Functor` I just can map a function over it. I was wrong as the `Graph` was the the `class` not the data type.

Any advice on an efficient way on how  to do this?

Thanks!

**Comment by snowleopard** [comment]
@adicirstei Hi there! 

`SymmetricRelation` is an instance of the type class `Graph` but it cannot be made an instance of `Functor` because it is internally represented by `Data.Set` which requires the `Ord a` constraint. 

We can define a function `gmap :: Ord b => (a -> b) -> SymmetricRelation a -> SymmetricRelation b` but it's not polymorphic enough to be used as `Functor`'s `fmap`.

In fact, we have `Relation.gmap`: 

https://github.com/snowleopard/alga/blob/master/src/Algebra/Graph/Relation.hs#L497-L510

So, we can easily add `SymmetricRelation.gmap` by wrapping and unwrapping the newtype. Will that work for you?

**Comment by snowleopard** [comment]
An alternative would be to add `Algebra.Graph.Undirected` that would be a simple wrapper around `Graph` data type defined in `Algebra.Graph`, which is a proper `Functor`.

Then we would be able to define the `instance Functor UndirectedGraph`.

**Comment by adicirstei** [comment]
What would involve doing `UndirectedGraph` ?

**Comment by snowleopard** [comment]
@adicirstei The simplest way forward is to define a `newtype`:

`newtype UndirectedGraph a = UndirectedGraph { graph :: Graph a } deriving (Functor, ... )` 

Then add a custom `Eq` instance, and modify a couple of graph algorithms to correctly deal with undirected edges. Most of the API of this module would simply redirect to the inner `graph`.

**Comment by adicirstei** [comment]
Great! I wasn’t sure how you were seeing it.

Adrian

**Comment by snowleopard** [comment]
@adicirstei Would you like to give this a try? I think it would be nice to add `Algebra.Graph.Undirected` to the library.

**Comment by snowleopard** [comment]
If anyone would like to attempt this, we now have `Symmetric.Relation` whose API can be followed:

https://hackage.haskell.org/package/algebraic-graphs-0.4/docs/Algebra-Graph-Relation-Symmetric.html

**Comment by bolt12** [comment]
@adicirstei are you working on this issue? If not, I'd be glad to give this a try!

**Comment by snowleopard** [comment]
@bolt12 No, this is independent from your symmetric relations work.

The implementation will be quite similar though: just add a newtype `Algebra.Graph.Undirected.Graph` wrapping the algebraic data type `Graph` and providing an API based on the one you implemented for symmetric relations.

**Comment by snowleopard** [comment]
> Also, could you walk me trough how do you use ghci/cabal new-repl?

For me both `ghci` and `stack ghci` seem to work.

P.S.: I assigned this issue to you. Thanks for volunteering! :)

**Comment by bolt12** [comment]
@snowleopard No problem! I'm happy to help!

That's odd, I'll try and refork the repo!

**Comment by bolt12** [comment]
@snowleopard sorry to bloat this thread with this issue but can you figure out how to solve this?
I reforked the repo and ran ghci on the project root:
![image](https://user-images.githubusercontent.com/20261421/60678405-44dd5500-9e7c-11e9-85a2-5ee2f3f4df61.png)

**Comment by snowleopard** [comment]
@bolt12 Not sure how to fix this at the moment. Let's fork this into a new issue.

**Comment by bolt12** [comment]
@snowleopard  looking into this. I built the project and ghci runs fine! `cabal new-repl` on the other hand cannot gives the same error but for QuickCheck. Probably it's because i'm unexperienced with the new version of cabal. I'll stick with ghci

**Comment by bolt12** [comment]
@snowleopard one question: should I use the Symmetric file as base or the Graph one? What would be preferable? Also the Graph one has rewrite rules and other stuff that I don't quite understand, but since it's a newtype I dont think I need to worry about them.

**Comment by snowleopard** [comment]
@bolt12 Yes, in general please follow the API of `Symmetric.Relation`.

Don't worry about the rewrite rules for now.

**Comment by snowleopard** [comment]
I think we can close this now, since the latest version has:

http://hackage.haskell.org/package/algebraic-graphs-0.5/docs/Algebra-Graph-Undirected.html

Thanks @bolt12!

**Comment by bolt12** [comment]
Awesome! You're welcome, it was a pleasure working with you in this PR!
