### ISSUE TITLE
Benchmark hasEdge

### ISSUE THREAD

**Issue by nobrakal** [snowleopard/alga#84]
Hi,

This is just for the record:

I saw: https://github.com/snowleopard/alga/blob/master/src/Algebra/Graph.hs#L449 : 

> -- TODO: Benchmark to see if this implementation is faster than the default
-- implementation provided by the ToGraph type class.

So here is the benchmarks:

`Alga` use the the ToGraph definition, `AlgaOld` is the current implementation:

## hasEdge

Description: Test if the given edge is in the graph (with arguments both in the graph and not in the graph (where applicable))

### Mesh
<TABLE>
   <TR>
      <TH>
      </TH>
      <TH CLASS = "thinright">
         1
      </TH>
      <TH CLASS = "thinright">
         10
      </TH>
      <TH CLASS = "thinright">
         100
      </TH>
      <TH>
         1000
      </TH>
   </TR>
   <TR>
      <TH>
         Alga
      </TH>
      <TD CLASS = "thinright">
         30.38 ns
      </TD>
      <TD CLASS = "thinright">
         783.9 ns
      </TD>
      <TD CLASS = "thinright">
         11.84 μs
      </TD>
      <TD>
         270.4 μs
      </TD>
   </TR>
   <TR>
      <TH>
         AlgaOld
      </TH>
      <TD CLASS = "thinright">
         385.7 ns
      </TD>
      <TD CLASS = "thinright">
         2.330 μs
      </TD>
      <TD CLASS = "thinright">
         19.89 μs
      </TD>
      <TD>
         219.1 μs
      </TD>
   </TR>
</TABLE>

### Clique
<TABLE>
   <TR>
      <TH>
      </TH>
      <TH CLASS = "thinright">
         1
      </TH>
      <TH CLASS = "thinright">
         10
      </TH>
      <TH CLASS = "thinright">
         100
      </TH>
      <TH>
         1000
      </TH>
   </TR>
   <TR>
      <TH>
         Alga
      </TH>
      <TD CLASS = "thinright">
         30.28 ns
      </TD>
      <TD CLASS = "thinright">
         2.733 μs
      </TD>
      <TD CLASS = "thinright">
         1.758 ms
      </TD>
      <TD>
         870.8 ms
      </TD>
   </TR>
   <TR>
      <TH>
         AlgaOld
      </TH>
      <TD CLASS = "thinright">
         384.7 ns
      </TD>
      <TD CLASS = "thinright">
         6.709 μs
      </TD>
      <TD CLASS = "thinright">
         588.7 μs
      </TD>
      <TD>
         94.03 ms
      </TD>
   </TR>
</TABLE>

SUMMARY:

 * Alga was the fastest 14 times
 * AlgaOld was the fastest 12 times

ABSTRACT:
(Based on an average of the ratio between largest benchmarks)

 * AlgaOld was 5.30 times faster than Alga

As the ToGraph option is faster on small graphs, I tried a combination of the two:

```Haskell
 hasEdge :: Ord a => a -> a -> Graph a -> Bool
hasEdge s t = (\g -> case foldg e v o c g of (_, _, r) -> r) . induce (`elem` [s, t])
   where
     e                             = (False   , False   , False                 )
     v x                           = (x == s  , x == t  , False                 )
     o (xs, xt, xst) (ys, yt, yst) = (xs || ys, xt || yt,             xst || yst)
     c (xs, xt, xst) (ys, yt, yst) = (xs || ys, xt || yt, xs && yt || xst || yst)
```

Which sadly is not better:
## hasEdge

Description: Test if the given edge is in the graph (with arguments both in the graph and not in the graph (where applicable))

### Mesh
<TABLE>
   <TR>
      <TH>
      </TH>
      <TH CLASS = "thinright">
         1
      </TH>
      <TH CLASS = "thinright">
         10
      </TH>
      <TH CLASS = "thinright">
         100
      </TH>
      <TH>
         1000
      </TH>
   </TR>
   <TR>
      <TH>
         Alga
      </TH>
      <TD CLASS = "thinright">
         61.87 ns
      </TD>
      <TD CLASS = "thinright">
         1.545 μs
      </TD>
      <TD CLASS = "thinright">
         18.95 μs
      </TD>
      <TD>
         210.9 μs
      </TD>
   </TR>
   <TR>
      <TH>
         AlgaOld
      </TH>
      <TD CLASS = "thinright">
         362.6 ns
      </TD>
      <TD CLASS = "thinright">
         2.288 μs
      </TD>
      <TD CLASS = "thinright">
         19.88 μs
      </TD>
      <TD>
         215.3 μs
      </TD>
   </TR>
</TABLE>

### Clique
<TABLE>
   <TR>
      <TH>
      </TH>
      <TH CLASS = "thinright">
         1
      </TH>
      <TH CLASS = "thinright">
         10
      </TH>
      <TH CLASS = "thinright">
         100
      </TH>
      <TH>
         1000
      </TH>
   </TR>
   <TR>
      <TH>
         Alga
      </TH>
      <TD CLASS = "thinright">
         62.05 ns
      </TD>
      <TD CLASS = "thinright">
         5.046 μs
      </TD>
      <TD CLASS = "thinright">
         541.8 μs
      </TD>
      <TD>
         123.9 ms
      </TD>
   </TR>
   <TR>
      <TH>
         AlgaOld
      </TH>
      <TD CLASS = "thinright">
         362.1 ns
      </TD>
      <TD CLASS = "thinright">
         6.668 μs
      </TD>
      <TD CLASS = "thinright">
         560.4 μs
      </TD>
      <TD>
         105.9 ms
      </TD>
   </TR>
</TABLE>

SUMMARY:

 * Alga was the fastest 10 times
 * AlgaOld was the fastest 3 times

 There was 13 ex-aequo

ABSTRACT:
(Based on an average of the ratio between largest benchmarks)

 * AlgaOld was 1.07 times faster than Alga

**Comment by snowleopard** [comment]
Interesting, thanks! I don't fully understand what you benchmarked, can you show the definition you used for the `Alga` (new)?

Could it be that we should specialise `ToGraph` code to `Graph` or simply copy the code?

**Comment by nobrakal** [comment]
Sorry if I wasn't clear.

For the FIRST table, I used (copy/pasted from ToGraph)
```Haskell
hasEdge s t g = case foldg e v o c g of (_, _, r) -> r
      where
        e                             = (False   , False   , False                 )
        v x                           = (x == s  , x == t  , False                 )
        o (xs, xt, xst) (ys, yt, yst) = (xs || ys, xt || yt,             xst || yst)
        c (xs, xt, xst) (ys, yt, yst) = (xs || ys, xt || yt, xs && yt || xst || yst)
```

For the SECOND, I used
```Haskell
hasEdge :: Ord a => a -> a -> Graph a -> Bool
hasEdge s t = (\g -> case foldg e v o c g of (_, _, r) -> r) . induce (`elem` [s, t])
   where
     e                             = (False   , False   , False                 )
     v x                           = (x == s  , x == t  , False                 )
     o (xs, xt, xst) (ys, yt, yst) = (xs || ys, xt || yt,             xst || yst)
     c (xs, xt, xst) (ys, yt, yst) = (xs || ys, xt || yt, xs && yt || xst || yst)
```

**Comment by snowleopard** [comment]
Wow, that's pretty surprising to me. So, essentially, on `clique` we get a 10x slowdown, and the only difference for `clique` is the term `xs && yt`.

What about making the third field (or maybe all of them) of the tuple strict? Perhaps, we are accumulating huge unevaluated trees of Boolean expressions in the process?

**Comment by nobrakal** [comment]
Sorry for taking so long to answer. Your implementation is faster but not enough:
### Clique
<TABLE>
   <TR>
      <TH>
      </TH>
      <TH>
         1000
      </TH>
   </TR>
   <TR>
      <TH>
         Alga
      </TH>
      <TD>
         692.3 ms
      </TD>
   </TR>
   <TR>
      <TH>
         AlgaOld
      </TH>
      <TD>
         94.69 ms
      </TD>
   </TR>
</TABLE>

Note that this is certainly the fault of `edges`. I have forget it, but I am running benchmarks using `edges`, and here not `clique. For example, with the `clique` from `alga`:

<TABLE>
   <TR>
      <TH>
      </TH>
      <TH>
         1000
      </TH>
   </TR>
   <TR>
      <TH>
         ToGraph
      </TH>
      <TD>
         58.46 μs
      </TD>
   </TR>
   <TR>
      <TH>
         ForcingValues
      </TH>
      <TD>
         61.72 μs
      </TD>
   </TR>
   <TR>
      <TH>
         Actual
      </TH>
      <TD>
         48.52 μs
      </TD>
   </TR>
</TABLE>

Anyway, one advantage of the `ToGraph` function is that it require only an _Eq_ instance, and not an _Ord_ one like the actual alga is requiring (because of the use of `isSubgraphOf`

**Comment by snowleopard** [comment]
> Note that this is certainly the fault of `edges`.

I don't understand what you mean: both algorithms are working on exactly the same input, right? It's not the fault of the input that one algorithm takes 10x longer than another :)

**Comment by nobrakal** [comment]
Mmh, yes your are right, I wanted to say to we must not forget that we are only using a very big stack of overlayed edges from `edges` :)

**Comment by snowleopard** [comment]
@nobrakal I don't think your `hasLoop` is correct, it will return `True` for `Connect Empty Empty` :) Unless, of course, you rely on the feature of (some) implementations of `induce` that do constant folding to eliminate `Empty` whenever possible.

**Comment by nobrakal** [comment]
Yep totally, I was thinking with `Algebra.Graph.i`Algebra.Graph.induce` which throw away empty leaves

**Comment by snowleopard** [comment]
@nobrakal Right, I see. I don't mind adding `hasLoop` into the API, so feel free to do that, but consistently across various modules.

So, what's the conclusion regarding `hasEdge`? I'm confused by so many different versions we discussed :) What is the most efficient implementation?

**Comment by nobrakal** [comment]
> I don't mind adding hasLoop into the API, so feel free to do that, but consistently across various modules.

You don't mind to do it _yourself_ but will merge if I do it ? I prefer to ask ^^

> So, what's the conclusion regarding hasEdge? I'm confused by so many different versions we discussed :) 

I was also ^^.

The actual one is the fastest, with graphs constructed with `edges` or with `clique`.
But a somewhat better version is:
```Haskell
hasEdge :: Eq a => a -> a -> Graph a -> Bool hasEdge u v = hasEdge' . induce (`elem` [u, v])
  where 
    hasEdge' (Overlay x y) = hasEdge' x || hasEdge' y 
    hasEdge' (Connect x y) = 
      let !isInLeft = hasVertex u x 
           !isInRight = hasVertex v y 
       in (isInLeft && isInRight) || (isInLeft && hasEdge' x) || (hasEdge' y && isInRight)
    hasEdge' _ = False
```

This improve a bit the time of the function (it is about `1.07` times faster), and mostly drop the `Ord` instance required on vertices because of `isSubgraphOf` in the current implementation. It is now only requiring `Eq`.
The "naive" implementation of `hasEdge'` works because the induced subgraph is very tiny thanks to the absence of `Empty` leaves

**Comment by snowleopard** [comment]
> You don't mind to do it yourself but will merge if I do it ? I prefer to ask ^^

I don't mind either, but I won't find time to do it myself in the next couple of weeks, so feel free to do it :-) 

OK, let's switch to your improved implementation -- it's not immediately obvious it is correct but it actually looks quite nice. Please send a PR!

**Comment by nobrakal** [comment]
I was going to send a PR, and while verifying my results, I benchmarked to `hasEdge'` function alone. It is quite better with graphs constructed with `edges`, but slower with `clique`: Here is the detailed benchmarks:

```Haskell
hasEdge :: Eq a => a -> a -> Graph a -> Bool
hasEdge u v = hasEdge'
  where
    hasEdge' (Overlay x y) = hasEdge' x || hasEdge' y
    hasEdge' (Connect x y) =
      let !isInLeft = hasVertex u x
          !isInRight = hasVertex v y
       in (isInLeft && isInRight) || (isInLeft && hasEdge' x) || (isInRight && hasEdge' y)
    hasEdge' _ = False
 ```

So without the suffixed `induce`. It is really faster hand drop the `Ord` instance:
```
### Clique
#### 1000
##### (0,1)

+---------++----------+-------+
|         ||     Time |    R² |
+=========++==========+=======+
|    Alga || 62.98 ns | 1.000 |
| AlgaOld || 96.58 ms | 0.966 |
+---------++----------+-------+

##### (292,820)

+---------++----------+-------+
|         ||     Time |    R² |
+=========++==========+=======+
|    Alga || 9.132 ms | 1.000 |
| AlgaOld || 96.28 ms | 0.984 |
+---------++----------+-------+

##### (997,999)

+---------++----------+-------+
|         ||     Time |    R² |
+=========++==========+=======+
|    Alga || 20.61 ms | 1.000 |
| AlgaOld || 98.32 ms | 0.980 |
+---------++----------+-------+

##### (0,0)

+---------++----------+-------+
|         ||     Time |    R² |
+=========++==========+=======+
|    Alga || 19.01 ms | 0.999 |
| AlgaOld || 92.89 ms | 0.982 |
+---------++----------+-------+

##### (1,0)

+---------++----------+-------+
|         ||     Time |    R² |
+=========++==========+=======+
|    Alga || 26.18 ms | 0.999 |
| AlgaOld || 88.50 ms | 0.975 |
+---------++----------+-------+

##### (1,1)

+---------++----------+-------+
|         ||     Time |    R² |
+=========++==========+=======+
|    Alga || 18.12 ms | 0.997 |
| AlgaOld || 91.48 ms | 0.983 |
+---------++----------+-------+
```

The first three tested edges are edges _in_ the graph, the last three are not in the graph.
Basically, in addition to being faster to find edges not in the graph, it is really faster to find edges "in the front" of the graph.

Sadly this is "less" true for graph constructed using `clique`, since it is slower for edges in the graph but "at the end", but faster in other cases:

```
### Clique
#### 1000
##### (0,1)

+---------++----------+-------+
|         ||     Time |    R² |
+=========++==========+=======+
|    Alga || 62.20 ns | 1.000 |
| AlgaOld || 46.53 μs | 1.000 |
+---------++----------+-------+

##### (292,820)

+---------++----------+-------+
|         ||     Time |    R² |
+=========++==========+=======+
| AlgaOld || 52.41 μs | 1.000 |
|    Alga || 2.486 ms | 1.000 |
+---------++----------+-------+

##### (997,999)

+---------++----------+-------+
|         ||     Time |    R² |
+=========++==========+=======+
| AlgaOld || 52.42 μs | 1.000 |
|    Alga || 5.969 ms | 0.999 |
+---------++----------+-------+

##### (0,0)

+---------++----------+-------+
|         ||     Time |    R² |
+=========++==========+=======+
|    Alga || 12.29 μs | 1.000 |
| AlgaOld || 46.69 μs | 1.000 |
+---------++----------+-------+

##### (1,0)

+---------++----------+-------+
|         ||     Time |    R² |
+=========++==========+=======+
|    Alga || 12.20 μs | 1.000 |
| AlgaOld || 45.93 μs | 0.999 |
+---------++----------+-------+

##### (1,1)

+---------++----------+-------+
|         ||     Time |    R² |
+=========++==========+=======+
|    Alga || 12.34 μs | 0.998 |
| AlgaOld || 47.13 μs | 1.000 |
+---------++----------+-------+
```

**Comment by snowleopard** [comment]
Wow, what happens here?
```
+---------++----------+-------+
|         ||     Time |    R² |
+=========++==========+=======+
| AlgaOld || 52.42 μs | 1.000 |
|    Alga || 5.969 ms | 0.999 |
+---------++----------+-------+
```
It's 100 times slower here! Could you investigate why?

**Comment by nobrakal** [comment]
The clique is in the form `Connect 0 (Connect 1 (Connect 2))`, so because I run `hasVertex` for every `Connect` node, this take very long time if we search an edge "at then end".

That is why it works great with #80 representation ^^
I suspect that it will be great fo "balanced" graphs, with similar of nodes on each part of a "Connect"...

**Comment by snowleopard** [comment]
Ah, of course -- the version that calls `hasVertex` actually has quadratic complexity. That's why I used triples in my implementation -- to memoize the invocations of `hasVertex`.

**Comment by snowleopard** [comment]
> So do you think we can approach the time of the version using hasVertex but using a better memoization ? 

Well, you are comparing an O(n) implementation against an O(n^2) one. Of course the latter will always lose on large benchmarks.

> Or even propose the two versions ?

I don't this there is any point in including a quadratic version into the library when there is a linear implementation. Think why the quadratic version manages to be faster on some examples -- perhaps that will help you figure out how to improve the linear version too!

**Comment by snowleopard** [comment]
@nobrakal Sorry, I'm not sure which implementation you refer to. Perhaps, just create a PR and we'll discuss it there :)

**Comment by nobrakal** [comment]
I think this is closed with your super version of `hasEdge` ?

**Comment by snowleopard** [comment]
@nobrakal Yes, thank you. I think we can close this.
