### ISSUE TITLE
Optimise size of mesh and torus

### ISSUE THREAD

**Issue by nobrakal** [snowleopard/alga#99]
Hi,

Working on #71 I just discovered that the `mesh` function is making graphs with a very big `size`:

```
> let m = mesh [1..10] [1..10] :: Graph (Int,Int)
> size m
685
> length $ edgeList m
180
> size $ edges $ edgeList m
361
```

One part of this is due to `Empty` graphs hidden at the end of each `path` (here `path` introduces `36` empty leaves), but there still a strange too big size :)
`box` seems to introduce duplicated edges...

**Comment by snowleopard** [comment]
Yes, `box` in general is not very efficient in terms of the size of the resulting expressions :) 

In principle, one could relatively easily obtain an efficient implementation of `mesh` without `box`, but I'd like to rename this issue to make it a bit more general.

**Comment by snowleopard** [comment]
One reason `box` is currently inefficient, is that it is fully polymorphic:
```haskell
box :: Graph a -> Graph b -> Graph (a, b)
box x y = overlays $ xs ++ ys
  where
    xs = map (\b -> fmap (,b) x) $ toList y
    ys = map (\a -> fmap (a,) y) $ toList x
```

Simply by switching from `toList` to `vertexList` in the implementation one could obtain a good improvement, but that requires `Ord a`.

**Comment by nobrakal** [comment]
Without requiring at least an `Eq` instance, we cannot distinct vertices, so I don't know if one can make an optimized `box`.

> one could relatively easily obtain an efficient implementation of mesh without box

It certainly affects `torus` as well, so it can worth it to have a better _polymorphic_ version of `mesh` and `torus` without relying on `box`.

**Comment by snowleopard** [comment]
> so it can worth it to have a better polymorphic version of `mesh` and `torus` without relying on `box`.

@nobrakal Yes, I think this is doable and the resulting functions are not going to be simple. Both `mesh` and `torus` could probably be expressed by using the `stars` combinator which was mentioned in the `edges` issue #71: just list all sources in a chessboard pattern, for example. But maybe there are even more compact representations -- an interesting puzzle :)

**Comment by nobrakal** [comment]
So for `mesh`: I came to something ugly version but it gives some results and can surely be prettified.

The idea is based on `edgesOrd` results, because it can actually reduce the size.
```Haskell
mesh :: [a] -> [b] -> Graph (a, b)
mesh xs ys = overlays $ map mkAngle [ (x, y) | x <- [0..lx] , y <- [0..ly] ]
  where
    mkAngle (x,y) g =
      let left =
            if x /= lx
               then Just $ vertex (xs !! (x+1), ys !! y)
               else Nothing
          up   =
            if y /= ly
               then Just $ vertex (xs !! x, ys !! (y+1))
               else Nothing
          modif (Just x) Nothing  = Just x
          modif Nothing (Just y)  = Just y
          modif (Just x) (Just y) = Just $ overlay x y
          modif Nothing Nothing   = Nothing
          curr = vertex (xs !! x, ys !! y)
       in maybe curr (connect curr g') $ modif up left
    lx = length xs - 1
    ly = length ys - 1
```

So what is behind this ugly code:

I chose to subdivide the graph into "angle". For each vertex, I want to draw an edge left and an edge up. I just have to avoid making an infinite `mesh`.

For example with a mesh with 9 vertices, I got:
```
1 * (2+4) + 2*(3+5)+ 3*6 + 4 * (5 + 7) + 5 * (6+8) + 6 * 9 + 7 * 8 + 8 * 9
```

Concerning size, we have, with `xs` and `ys` two lists (with more than 1 element) with `m` and `n` their size:

```
> let a = size (mesh xs ys) 
a == 3*(m-1)*(n-1)+2*(m+n-2)+1+1
```

while:

```
> let b = size (edges $ edgeList $ mesh xs ys) 
b == 2*((m-1)*n+(n-1)*m) + 1 
```

Not obviously, we have the relation

```
b - a == m*n - m - n
```

So it seems like an improvement :) 

The same idea can apply for `torus` with even more simplification, because we will not overlay angle but something like a cross for the most of vertices (and can already see `star` in this code).

**Comment by nobrakal** [comment]
For `torus` things are easier:
```Haskell
torus :: [a] -> [b] -> Graph (a, b)
torus xs ys = overlays $ map mkAngle [ (x, y) | x <- [0..(lx-1)] , y <- [0..(ly-1)] ]
  where
    mkAngle (x,y) =
      let left = vertex (xs !! ((x + 1) `mod` lx), ys !! y)
          up   = vertex (xs !! x, ys !! ((y + 1) `mod` ly))
          curr = vertex (xs !! x, ys !! y)
       in connect curr $ overlay up left
    lx = length xs
    ly = length ys
```

The size bounds, with `xs` and `ys` two lists and `m` and `n` their size:

```
> size (torus xs ys) 
3*m*n + 1
```

while:

```
> size (edges $ edgeList $ torus xs ys) 
4*m*n + 1
```

(Actually:  `size (edges $ edgeList $ torus xs ys)  == size (torus xs ys)` ).

So this version is more obviously an improvement concerning size :)

Note that I don't used `stars`, because it is `overlays`-based and thus add an empty leaf at the end of every "angle".

**Comment by snowleopard** [comment]
@nobrakal I don't see any difference from `stars`: you just overlay a large number of `star curr [up, left]`. So, I'd say `stars` fits here too.

**Comment by snowleopard** [comment]
By the way, I just realised that we already have `stars` but we call it `fromAdjacencyList` :-) I am going to rename it -- will send a PR soon.

**Comment by nobrakal** [comment]
@snowleopard The problem with `star` comes from `vertices` which includes an empty leaf at the end of all `star`.

Here I know that the lists will be non empty, thus I avoid this empty leaf by a custom implementation of `star`.

**Comment by snowleopard** [comment]
@nobrakal Perhaps, we could find a way to implement `vertices` without an empty leaf at the end? That would be useful for many other functions. I remember we had some performance issues with this, but perhaps now that you have more experience in GHC optimisations, you'll be able to solve this? :)

**Comment by snowleopard** [comment]
@nobrakal That's awesome! Looks like Alga is a good library for learning all GHC optimisation tricks :) There may be a separate blog post just about fusing various graph functions!

**Comment by nobrakal** [comment]
Using `stars`:
```Haskell
mesh :: [a] -> [b] -> Graph (a, b)
mesh xs ys = stars $ map mkAngle [ (x, y) | x <- [0..lx] , y <- [0..ly] ]
  where
    mkAngle (x,y) =
      let left = [(xs !! (x+1), ys !! y) | x /= lx]
          up   = [(xs !! x, ys !! (y+1)) | y /= ly]
          curr = (xs !! x, ys !! y)
       in (curr, up ++ left)
    lx = length xs - 1
    ly = length ys - 1

torus :: [a] -> [b] -> Graph (a, b)
torus xs ys = stars $ map mkAngle [ (x, y) | x <- [0..(lx-1)] , y <- [0..(ly-1)] ]
  where
    mkAngle (x,y) =
      let left = (xs !! ((x + 1) `mod` lx), ys !! y)
          up   = (xs !! x, ys !! ((y + 1) `mod` ly))
          curr = (xs !! x, ys !! y)
       in (curr, [up,left])
    lx = length xs
ly = length ys
```

More pretty code :)

**Comment by snowleopard** [comment]
@nobrakal The prolifiration of slow operators `!!` is somewhat worrying -- your implementation is going to be slower than the original one.

Could you get rid of indexing?

Here is (roughly) what you could do:

```haskell
-- Be careful with empty lists
pairs :: [a] -> [(a, a)]
pairs as = zip as (tail as)

grid :: [a] -> [b] -> [((a, a), (b, b))]
grid as bs = [ (pa, pb) | pa <- pairs as, pb <- pairs pb ]
```

And then you could do something like:

```haskell
stars [ ((a1, b1), [(a1, b2), (a2, b1)] | ((a1, a2), (b1, b2) <- grid ]
```

**Comment by nobrakal** [comment]
> Could you get rid of indexing?

For `torus` it is simple (with an improved `pairs`):
```Haskell
pairs :: [a] -> [(a, a)]
pairs [] = []
pairs as@(x:xs) = zip as (xs ++ [x])

torus :: [a] -> [b] -> Graph (a, b)
torus xs ys = stars [ ((a1, b1), [(a1, b2), (a2, b1)]) | (a1, a2) <- pairs xs, (b1, b2) <- pairs ys ]
```


Sadly, the structure of a `mesh` don't allow me to do such a simple thing:
```Haskell
mesh :: [a] -> [b] -> Graph (a, b)
mesh []  _   = empty
mesh _   []  = empty
mesh [x] [y] = vertex (x, y)
mesh xs  ys  = stars $  [ ((a1, b1), [(a1, b2), (a2, b1)]) | (a1, a2) <- ipxs, (b1, b2) <- ipys ]
                     ++ [ ((lx,y1), [(lx,y2)]) | (y1,y2) <- ipys]
                     ++ [ ((x1,ly), [(x2,ly)]) | (x1,x2) <- ipxs]
  where
    lx = last xs
    ly = last ys
    ipxs = init (pairs xs)
    ipys = init (pairs ys)
```

**Comment by snowleopard** [comment]
Aha, `torus` looks good.

In `mesh`, perhaps you could do `stars` plus a couple of `path`s for the right and bottom layers? That may be easier to understand, and should be optimal size-wise.

**Comment by nobrakal** [comment]
@snowleopard 
Something like this ?

```Haskell
mesh []  _   = empty
mesh _   []  = empty
mesh [x] [y] = vertex (x, y)
mesh xs  ys  = stars [ ((a1, b1), [(a1, b2), (a2, b1)]) | (a1, a2) <- ipxs, (b1, b2) <- ipys ]
     `overlay` path [ ((lx,y1), (lx,y2)) | (y1,y2) <- ipys]
     `overlay` path [ ((x1,ly), (x2,ly)) | (x1,x2) <- ipxs]
  where
    lx = last xs
    ly = last ys
    ipxs = init (pairs xs)
    ipys = init (pairs ys)
```

**Comment by snowleopard** [comment]
Yes, looks good! I might tweak it further, but feel free to send a PR.

**Comment by nobrakal** [comment]
I prefer to wait for #103 to be merged before, since size bound will explode with all the empty leaves of `overlays`:)

**Comment by snowleopard** [comment]
@nobrakal Sure :)

**Comment by snowleopard** [comment]
I believe #110 resolved this.
